spring:
  application:
    name: fitguru-backend

  datasource:
    url: jdbc:postgresql://localhost:5433/fitguru
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080